services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learn_nestjs-app
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    env_file:
      - .env.development
    environment:
      DB_HOST: mysql
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - learn_nestjs-network
    command: yarn start:dev

  mysql:
    image: mysql:8.0
    container_name: learn_nestjs-mysql-db
    platform: linux/x86_64
    ports:
      - "33306:3306"
    environment:
      MYSQL_DATABASE: learn_nestjs
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - learn_nestjs-network

volumes:
  mysql_data:

networks:
  learn_nestjs-network:
    external: true
