const COMPARE_TYPES = {
  AND: 'and',
  OR: 'or',
};

const META_DATA_KEY = 'permissions';

const PERMISSION_AUTH = {
  ALL: 'ALL',
  PERMISSION: {
    CREATE: 'PERMISSION.CREATE',
    DELETE: 'PERMISSION.DELETE',
    UPDATE: 'PERMISSION.UPDATE',
    VIEW: {
      ALL: 'PERMISSION.VIEW.ALL',
      MULTIPLE: 'PERMISSION.VIEW.MULTIPLE',
    },
  },
  ROLE: {
    CREATE: 'ROLE.CREATE',
    DELETE: 'ROLE.DELETE',
    UPDATE: 'ROLE.UPDATE',
    VIEW: {
      ALL: 'ROLE.VIEW.ALL',
      MULTIPLE: 'ROLE.VIEW.MULTIPLE',
    },
  },
  USER: {
    CREATE: 'USER.CREATE',
    DELETE: 'USER.DELETE',
    UPDATE: 'USER.UPDATE',
    VIEW: {
      ALL: 'USER.VIEW.ALL',
      MULTIPLE: 'USER.VIEW.MULTIPLE',
    },
  },
};

export { COMPARE_TYPES, META_DATA_KEY, PERMISSION_AUTH };
